let gokupetit = new Carte("Goku Petit", 5, 3, 20, "Rage", "B", "Attaque deux fois en dessous de 8 pv","img/cartes/gokukid.webp")
let tortuegeniale = new Carte("Tortue Géniale", 6, 1, 18, "Petit vicieux", "B", "Esquive une attaque et rend un coup léger.","img/cartes/tortuegeniale.webp")
let bulma = new Carte("Bulma", 2, 3, 15, "ingénierie", "B", "Copie le spéciale de la carte adverse.","img/cartes/bulma.webp")
let krilin = new Carte("Krilin", 4, 3, 20, "Boule de billard", "B", "Renvoi une attaque complète.","img/cartes/krilin.webp")
let shenron = new Carte("shenron", 1, 1, 10, "Espoir", "S", "Ressuscite la carte ko précédente.","img/cartes/shenron.webp")
